name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    
jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Setup the code
      run: npm install
    - name: Test the code
      run: npm test
    - name: Deploy to Firebase
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
          repoToken: "${{ secrets.REPO_ACCESS_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          projectId: your-Firebase-project-ID
          channelId: live
